services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - no-internet

  database:
    image: mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      - MONGO_INITDB_DATABASE=inmutatio
      - MONGO_INITDB_ROOT_USERNAME=inmutatio
      - MONGO_INITDB_ROOT_PASSWORD=inmutatio
    networks:
      - no-internet

  express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=inmutatio
      - ME_CONFIG_MONGODB_ADMINPASSWORD=inmutatio
    #links:
    #  - "database:database"
    depends_on:
      - database
    networks:
      - no-internet
      - backend

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - 8083:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - no-internet
      - backend

  api:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    depends_on:
      - redis
      - database
    ports:
      - 8080:7117
    networks:
      - no-internet
      - backend
    command: npm run start-backend
    restart: always

networks:
  frontend:
    name: "frontend"
  backend:
    name: "backend"
  no-internet:
    name: "no-internet"
    internal: true